/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thinking_cameraimput_FrameHandler */

#ifndef _Included_com_thinking_cameraimput_FrameHandler
#define _Included_com_thinking_cameraimput_FrameHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef com_thinking_cameraimput_FrameHandler_MIN_PRIORITY
#define com_thinking_cameraimput_FrameHandler_MIN_PRIORITY 1L
#undef com_thinking_cameraimput_FrameHandler_NORM_PRIORITY
#define com_thinking_cameraimput_FrameHandler_NORM_PRIORITY 5L
#undef com_thinking_cameraimput_FrameHandler_MAX_PRIORITY
#define com_thinking_cameraimput_FrameHandler_MAX_PRIORITY 10L
	/*
	 * Class:     com_thinking_cameraimput_FrameHandler
	 * Method:    handle_frame
	 * Signature: (III[B[I)V
	 */
	JNIEXPORT void JNICALL Java_com_thinking_cameraimput_FrameHandler_handle_1frame
		(JNIEnv *, jclass, jint, jint, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
