/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/contrib/contrib.hpp>
/* Header for class com_thinking_edgedetectionfilter_ImageHandler */

#ifndef _Included_com_thinking_edgedetectionfilter_ImageHandler
#define _Included_com_thinking_edgedetectionfilter_ImageHandler
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_thinking_edgedetectionfilter_ImageHandler
	 * Method:    get_image_laplacian
	 * Signature: (Lcom/thinking/edgedetectionfilter/ImageHandler/ImageData;Lcom/thinking/edgedetectionfilter/ImageHandler/Listener;)V
	 */
	JNIEXPORT void JNICALL Java_com_thinking_edgedetectionfilter_ImageHandler_get_1image_1laplacian
		(JNIEnv *, jclass, jobject, jobject);

	/*
	 * Class:     com_thinking_edgedetectionfilter_ImageHandler
	 * Method:    get_image_scharr
	 * Signature: (Lcom/thinking/edgedetectionfilter/ImageHandler/ImageData;Lcom/thinking/edgedetectionfilter/ImageHandler/Listener;)V
	 */
	JNIEXPORT void JNICALL Java_com_thinking_edgedetectionfilter_ImageHandler_get_1image_1scharr
		(JNIEnv *, jclass, jobject, jobject);

	/*
	 * Class:     com_thinking_edgedetectionfilter_ImageHandler
	 * Method:    get_image_change_bk
	 * Signature: (Lcom/thinking/edgedetectionfilter/ImageHandler/ImageData;Lcom/thinking/edgedetectionfilter/ImageHandler/Listener;)V
	 */
	JNIEXPORT void JNICALL Java_com_thinking_edgedetectionfilter_ImageHandler_get_1image_1change_1bk
		(JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
