/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thinking_edgedetectionfilter_ImageHandler_ImageData */

#ifndef _Included_com_thinking_edgedetectionfilter_ImageHandler_ImageData
#define _Included_com_thinking_edgedetectionfilter_ImageHandler_ImageData
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
