/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/contrib/contrib.hpp>

using namespace std;
using namespace cv;
/* Header for class com_thinking_imagesegmentation_ImageHandler */

#ifndef _Included_com_thinking_imagesegmentation_ImageHandler
#define _Included_com_thinking_imagesegmentation_ImageHandler
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_thinking_imagesegmentation_ImageHandler
	 * Method:    getRectangleObj
	 * Signature: (Lcom/thinking/imagesegmentation/ImageHandler/ImageData;Lcom/thinking/imagesegmentation/ImageHandler/Listener;)V
	 */
	JNIEXPORT void JNICALL Java_com_thinking_imagesegmentation_ImageHandler_getRectangleObj
		(JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
