/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/contrib/contrib.hpp>

using namespace std;
using namespace cv;
/* Header for class com_thinking_imagesegmentation_camera_FrameHandler */

#ifndef _Included_com_thinking_imagesegmentation_camera_FrameHandler
#define _Included_com_thinking_imagesegmentation_camera_FrameHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef com_thinking_imagesegmentation_camera_FrameHandler_MIN_PRIORITY
#define com_thinking_imagesegmentation_camera_FrameHandler_MIN_PRIORITY 1L
#undef com_thinking_imagesegmentation_camera_FrameHandler_NORM_PRIORITY
#define com_thinking_imagesegmentation_camera_FrameHandler_NORM_PRIORITY 5L
#undef com_thinking_imagesegmentation_camera_FrameHandler_MAX_PRIORITY
#define com_thinking_imagesegmentation_camera_FrameHandler_MAX_PRIORITY 10L
	/*
	 * Class:     com_thinking_imagesegmentation_camera_FrameHandler
	 * Method:    handle_frame
	 * Signature: (IIZ[B[I)V
	 */
	JNIEXPORT void JNICALL Java_com_thinking_imagesegmentation_camera_FrameHandler_handle_1frame
		(JNIEnv *, jclass, jint, jint, jboolean, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
