/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thinking_imagesegmentation_ImageHandler_Listener */

#ifndef _Included_com_thinking_imagesegmentation_ImageHandler_Listener
#define _Included_com_thinking_imagesegmentation_ImageHandler_Listener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
