/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thinking_skindetection_SkinHandler_Position */

#ifndef _Included_com_thinking_skindetection_SkinHandler_Position
#define _Included_com_thinking_skindetection_SkinHandler_Position
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
