/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thinking_imageinput_NdkTools */

#ifndef _Included_com_thinking_imageinput_NdkTools
#define _Included_com_thinking_imageinput_NdkTools
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_thinking_imageinput_NdkTools
	 * Method:    test_image_data_input
	 * Signature: (Lcom/thinking/imageinput/NdkTools/ImageData;)[I
	 */
	JNIEXPORT jintArray JNICALL Java_com_thinking_imageinput_NdkTools_test_1image_1data_1input
		(JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
